services:
  - type: web
    name: quiz-hub
    env: node
    rootDir: new/oware-quiz-hub
    buildCommand: |
      cd new/oware-quiz-hub
      npm install
      npm run build
    startCommand: |
      cd new/oware-quiz-hub
      npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: ""
      - key: DB_NAME
        value: quiz_db
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0 